"""init

Revision ID: ef4f95ae9296
Revises: 4739591b3c5d
Create Date: 2023-12-11 18:18:15.720133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef4f95ae9296'
down_revision = '4739591b3c5d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
